variables:
  SECRET_KEY: ${SECRET_KEY}
  DEBUG: True
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  USERNAME: ${USERNAME}
  PASSWORD: ${PASSWORD}

default:
  image: python:latest

stages:
  - build
  - test
  - package
  - deploy

cache:
  paths:
        - .cache/pip
  key: "$CI_JOB_NAME"

compilation:
  stage: build
  before_script:
  - pip install -r requirements.txt
  script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py check

tests:
  stage: test
  before_script:
  - pip install -r requirements.txt
  script:
    - python manage.py test

coverage:
  stage: test
  before_script:
  - pip install -r requirements.txt
  script:
    - pytest --cov=. --cov-report term --cov-report xml:coverage.xml
    - echo "Coverage test over with no issues" 
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  
linting:
  stage: test
  before_script:
  - pip install -r requirements.txt
  script:
    - flake8
    - echo "No lint issues found."

packaging:
  stage: package
  image: docker:stable
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login --username $DOCKER_HUB_USERNAME --password-stdin
    - docker build -t $DOCKER_HUB_USERNAME/$CI_COMMIT_SHORT_SHA .
    - docker push $DOCKER_HUB_USERNAME/$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  image: alpine
  script:
    - apk add --no-cache curl
    - curl -X POST -H "Autorization: Bearer $RENDER_API_TOKEN" "$RENDER_API_URL/services/$RENDER_SERVICE_NAME/deploy"
  only:
  - main