services:
  - type: web
    plan: free
    name: mysite
    runtime: docker
    buildCommand: "./build.sh"
    startCommand: "python manage.py runserver"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4