services:
  - name: oc_lettings_site 
  - type: web
 env: docker
 buildCommand: docker build . 
 startCommand: docker run
 dockerfilePath: ./Dockerfile
 envVars:
  - key: ALLOWED_HOSTS
    value: ['*']
  - key: DEBUG
    value: False