services:
  - type: web
    plan: free
    name: oc_lettings
    runtime: python 
    buildCommand: "./build.sh"
    startCommand: "python manage.py runserver 0.0.0.0:8000"
    envVars:
    - key: SECRET_KEY
      generateValue: true
    - key: ALLOWED_HOSTS
      value: '*'